New upstream version 2.7.0~preview1

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,3 +1,5 @@
+# -*- mode: makefile-gmake; indent-tabs-mode: t -*-
+
 SHELL = /bin/sh
 NULLCMD = @NULLCMD@
 n=$(NULLCMD)
@@ -123,7 +125,6 @@ BUILTIN_TRANSOBJS = @BUILTIN_TRANSOBJS@
 POSTLINK = @POSTLINK@
 
 RUBY_BASE_NAME=@RUBY_BASE_NAME@
-RUBY_PROGRAM_VERSION=@RUBY_PROGRAM_VERSION@
 RUBY_API_VERSION=@RUBY_API_VERSION@
 RUBY_INSTALL_NAME=@RUBY_INSTALL_NAME@
 RUBY_SO_NAME=@RUBY_SO_NAME@
@@ -159,7 +160,9 @@ COROUTINE_OBJ = $(COROUTINE_H:.h=.@OBJEXT@)
 MAJOR=	@MAJOR@
 MINOR=	@MINOR@
 TEENY=	@TEENY@
-RUBY_PROGRAM_VERSION = @RUBY_PROGRAM_VERSION@
+
+# here for MJIT_MIN_HEADER_NAME, not in common.mk
+RUBY_PROGRAM_VERSION = $(MAJOR).$(MINOR).$(TEENY)
 
 LIBRUBY_A     = @LIBRUBY_A@
 LIBRUBY_SO    = @LIBRUBY_SO@
@@ -357,7 +360,6 @@ reconfig-exec-1 = set -x; "$$@"
 reconfig config.status:	$(srcdir)/$(CONFIGURE) $(srcdir)/enc/Makefile.in \
 			$(srcdir)/include/ruby/version.h
 	@PWD= MINIRUBY="$(MINIRUBY)"; export MINIRUBY; \
-	warnflags="@warnflags@"; export warnflags; \
 	set $(SHELL) $($@-args); $(reconfig-exec-$(V))
 
 $(srcdir)/$(CONFIGURE): $(srcdir)/configure.ac $(srcdir)/aclocal.m4
@@ -417,7 +419,7 @@ $(srcdir)/enc/jis/props.h: enc/jis/props.kwd
 
 .$(ASMEXT).@OBJEXT@:
 	@$(ECHO) assembling $<
-	$(Q) $(CC) $(ASFLAGS) -o $@ -c $<
+	$(Q) $(CC) $(ASFLAGS) -DSYMBOL_PREFIX=$(SYMBOL_PREFIX) -o $@ -c $<
 
 .c.$(ASMEXT):
 	@$(ECHO) translating $<
@@ -478,9 +480,9 @@ distclean-local::
 	-$(Q)$(RM) $(INSTALLED_LIST) $(arch_hdrdir)/ruby/config.h verconf.h
 	-$(Q)$(RMDIRS) $(arch_hdrdir)/ruby 2> /dev/null || true
 
-ext/clean.sub gems/clean.sub:: ext/clean.mk
-ext/distclean.sub gems/distclean.sub:: ext/distclean.mk
-ext/realclean.sub gems/realclean.sub:: ext/realclean.mk
+ext/clean.sub:: ext/clean.mk
+ext/distclean.sub:: ext/distclean.mk
+ext/realclean.sub:: ext/realclean.mk
 
 ext/clean.mk ext/distclean.mk ext/realclean.mk::
 	-$(Q) if [ -f $(EXTS_MK) ]; then exec $(MAKE) -f $(EXTS_MK) $(@F:.mk=); fi
@@ -529,10 +531,17 @@ enc/encinit.$(OBJEXT): enc/encinit.c $(SETUP)
 
 cont.$(OBJEXT): $(COROUTINE_H)
 
+# Override this to allow failure of specific gems on CI
+TEST_BUNDLED_GEMS_ALLOW_FAILURES =
+
 test-bundled-gems-run:
 	$(Q) set -e; while read gem _; do \
-	  echo testing $$gem gem && \
-	  $(XRUBY) -C $(srcdir)/gems/src/$$gem -Ilib ../../../.bundle/bin/rake; \
+	  echo testing $$gem gem; \
+	  if echo $(TEST_BUNDLED_GEMS_ALLOW_FAILURES) | grep -q $$gem; then \
+	    $(XRUBY) -C $(srcdir)/gems/src/$$gem -Ilib ../../../.bundle/bin/rake || true; \
+	  else \
+	    $(XRUBY) -C $(srcdir)/gems/src/$$gem -Ilib ../../../.bundle/bin/rake; \
+	  fi; \
 	done < $(srcdir)/gems/bundled_gems
 
 update-src::
@@ -631,3 +640,7 @@ mjit_build_dir.$(SOEXT): $(MJIT_MIN_HEADER) $(srcdir)/ruby-runner.c ruby-runner.
 	$(Q) $(DLDSHARED) $(MJIT_DLDFLAGS) $(ARCH_FLAG) $(CFLAGS) $(CPPFLAGS) \
 		-DMAKE_MJIT_BUILD_DIR=1 -DMJIT_MIN_HEADER='"$(MJIT_MIN_HEADER)"' \
 		$(OUTFLAG)$@ $(srcdir)/ruby-runner.c
+
+# yes-test-basic: leaked-globals
+leaked-globals: $(COMMONOBJS) prog $(srcdir)/tool/leaked-globals PHONY
+	$(Q) $(XRUBY) $(srcdir)/tool/leaked-globals NM=$(NM) SYMBOL_PREFIX=$(SYMBOL_PREFIX) $(srcdir)/configure.ac $(COMMONOBJS)
